/* eslint-disable @typescript-eslint/no-explicit-any */
import AccessTimeRoundedIcon from "@mui/icons-material/AccessTimeRounded";
import CloseSharpIcon from "@mui/icons-material/CloseSharp";
import { Backdrop, CircularProgress } from "@mui/material";
import axios from "axios";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useQuery } from "react-query";

import Shell from "@components/Shell";
import Sidebar from "@components/shared/Sidebar";

const Bookings = () => {
  const { data: session } = useSession();
  const getAllEvents = async () => {
    if (session !== undefined && session !== null) {
      const { data } = await axios.get(`/api/events/${session.id}`);
      return data;
    } else {
      const { data } = await axios.get("/api/events");
      return data;
    }
  };

  const { data, isLoading } = useQuery("events", getAllEvents);

  if (isLoading) {
    return (
      <Backdrop sx={{ color: "#fff", zIndex: (theme) => theme.zIndex.drawer + 1 }} open={isLoading}>
        <CircularProgress color="inherit" />
      </Backdrop>
    );
  }

  return (
    <Shell>
      <div className="flex flex-row items-start justify-between">
        <Head>
          <title>Bookings | Cal.com</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Sidebar />
        <div className="h-screen w-[80%] bg-secondary p-12 flex flex-col">
          <div className="flex flex-col items-start justify-center">
            <span className="text-base font-bold">Bookings</span>
            <span className="text-gray-500">
              See upcoming and past events booked through your event type links.
            </span>
          </div>
          <div className="flex flex-row items-center w-full my-5">
            <ul className="flex flex-row items-center">
              <li className="mr-5">
                <a href="#">Upcoming</a>
              </li>
              <li className="mx-5">
                <a href="#">Past</a>
              </li>
              <li className="mx-5">
                <a href="#">Cancelled</a>
              </li>
            </ul>
          </div>
          <div className="w-full h-px bg-primary" />
          {data.data.map((event: any) => (
            <div
              className="flex flex-row items-center justify-between w-full px-5 py-5 mt-10 bg-white border-2 border-secondary"
              key={event.id}>
              <div className="flex flex-col justify-between cursor-pointer">
                <div className="flex flex-row my-2 text-xs">
                  <span className="font-bold">{event.date}</span>
                  <span className="ml-3 font-semibold">
                    Secret Meeting between {event.name} and {event.eventType.user.name}
                  </span>
                </div>
                <div className="flex flex-row items-center justify-start my-2 text-xs">
                  <span className="ml-1 mr-3 text-gray-300">{event.time}-</span>

                  <span className="ml-1 text-gray-300">{event.time}</span>
                </div>
              </div>
              <div className="flex flex-row justify-between">
                <a
                  target="_blank"
                  href="/dushimeemma/15min"
                  className="flex items-center justify-center px-3 py-2 mx-5 border-2 border-secondary">
                  <CloseSharpIcon width={15} height={15} className="mr-2" /> Cancel
                </a>
                <button
                  type="button"
                  className="flex items-center justify-center px-3 py-2 mx-5 border-2 border-secondary">
                  <AccessTimeRoundedIcon width={15} height={15} className="mr-2" />
                  Reschedule
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </Shell>
  );
};

export default Bookings;
